-- 通用 AI 动作计划、人工确认、幂等执行和审计记录。
-- 脚本可重复执行，不修改或删除既有业务数据。

CREATE TABLE IF NOT EXISTS edu_ai_action (
    id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    capability_id VARCHAR(128) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL,
    risk_level VARCHAR(16) NOT NULL,
    confirmation_policy VARCHAR(32) NOT NULL,
    target_type VARCHAR(64) NULL,
    target_id BIGINT NULL,
    target_version INT NULL,
    title VARCHAR(200) NOT NULL,
    summary VARCHAR(1000) NOT NULL,
    parameters_json TEXT NOT NULL,
    preview_json TEXT NOT NULL,
    result_json TEXT NULL,
    resource_type VARCHAR(64) NULL,
    resource_id BIGINT NULL,
    resource_href VARCHAR(500) NULL,
    trace_id VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    expires_at DATETIME(3) NOT NULL,
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME(3) NULL,
    executed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    created_by BIGINT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    updated_by BIGINT NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_ai_action_idempotency UNIQUE (idempotency_key),
    INDEX idx_ai_action_requester (requester_id, role_code, status, deleted, created_at, id),
    INDEX idx_ai_action_capability (capability_id, status, deleted, created_at, id),
    INDEX idx_ai_action_target (target_type, target_id, status, deleted, id)
);
