/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistButton: typeof import('./src/components/AiAssistButton.vue')['default']
    AiResultPanel: typeof import('./src/components/AiResultPanel.vue')['default']
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppMetric: typeof import('./src/components/AppMetric.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AsyncState: typeof import('./src/components/AsyncState.vue')['default']
    FChart: typeof import('./src/components/FChart.vue')['default']
    GlobalAiAssistant: typeof import('./src/components/GlobalAiAssistant.vue')['default']
    NotificationDrawer: typeof import('./src/components/NotificationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/StatusBadge.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
